### PR TITLE
Fix cog bosses like vp , cfo, cj and ceo

### PR DESCRIPTION
**Pull request by mgracer48**
Little Ned: Credit goes towards @mgracer48 for fixing it

[Review on Reviewable](https://reviewable.io/reviews/toontownstrideofficial/toontownstride/7)

### CODE REVIEW

**Comment by LittleNed** [comment]
it was 100% him ^.^

**Comment by LittleNed** [comment]
thanks mgracer48 100% credit

**Comment by ToontownStrideOfficial** [comment]
Thanks for this fix! Feel free to provide more if you encounter any bugs :)

**Comment by mgracer48** [comment]
No problem

**Pull request merged**
